sonar.projectKey=three-tier-devops-project

sonar.sources=.

sonar.javascript.lcov.reportPaths=src/backend/coverage/lcov.info,src/frontend/coverage/lcov.info


# Ignore unwanted files
sonar.exclusions=\
**/node_modules/**,\
**/coverage/**,\
**/build/**,\
**/dist/**,\
**/*.png,\
**/*.jpg,\
**/*.jpeg,\
**/*.wasm


sonar.sourceEncoding=UTF-8
