sonar.projectKey=three-tier-devops-project

sonar.sources=src/backend,src/frontend,terraform,k8s

sonar.javascript.lcov.reportPaths=\
src/backend/coverage/lcov.info,\
src/frontend/coverage/lcov.info


sonar.exclusions=\
**/node_modules/**,\
**/coverage/**,\
**/build/**,\
**/dist/**,\
**/*.png,\
**/*.jpg,\
**/*.jpeg,\
**/*.wasm

sonar.sourceEncoding=UTF-8
