sonar.sources=src/backend,src/frontend,terraform,k8s

sonar.exclusions=**/node_modules/**,
                 **/coverage/**,
                 **/build/**,
                 **/dist/**,
                 **/*.png,
                 **/*.jpg
                 
sonar.sourceEncoding=UTF-8
